<a href="https://colab.research.google.com/github/huzaifabaloch/Huzaifa_AIC020241/blob/master/DigitsMnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install --upgrade tensorflow==2.0

     |████████████████████████████████| 86.3MB 65kB/s 
     |████████████████████████████████| 3.8MB 44.8MB/s 
     |████████████████████████████████| 450kB 32.9MB/s 
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstalled tensorflow-1.15.0


In [37]:
import tensorflow as tf
print(tf.__version__)

2.0.0


In [0]:
from keras.datasets import mnist

In [0]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [69]:
train_images.shape

(60000, 28, 28)

In [70]:
type(train_labels)

numpy.ndarray

In [71]:
train_images[0].shape

(28, 28)

In [72]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [73]:
test_images.shape

(10000, 28, 28)

In [74]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [0]:
from tensorflow.keras import models
from tensorflow.keras import layers

In [0]:
network = models.Sequential()
network.add(layers.Dense(512, activation='relu',  input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [0]:
  network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [0]:
train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype('float') / 255

In [0]:
test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype('float') / 255

In [0]:
from keras.utils import to_categorical

In [0]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [82]:
train_labels[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [83]:
network.fit(train_images, train_labels, batch_size=128, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 6s 105us/sample - loss: 0.2549 - accuracy: 0.9255
Epoch 2/5
60000/60000 [==============================] - 6s 93us/sample - loss: 0.1048 - accuracy: 0.9688
Epoch 3/5
60000/60000 [==============================] - 6s 92us/sample - loss: 0.0691 - accuracy: 0.9797
Epoch 4/5
60000/60000 [==============================] - 6s 94us/sample - loss: 0.0499 - accuracy: 0.9848
Epoch 5/5
60000/60000 [==============================] - 5s 92us/sample - loss: 0.0381 - accuracy: 0.9884


In [84]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

In [86]:
print(test_acc)

0.9813
